### ISSUE TITLE
NullPointerException in yaml:IndentationCheck

### ISSUE THREAD

**Issue by roglar** [sbaudoin/yamllint#11] opened 2020-02-03 16:35 UTC
[first reported to Sonarsource](https://community.sonarsource.com/t/nullpointerexception-in-yaml-indentationcheck/19578)

versions used (SonarQube, Scanner, Plugin, and any relevant extension)
SonarQube 7.9.2 (build 30863)
sonar-maven-plugin 3.7.0.1746

error observed

```
Caused by: java.lang.NullPointerException
Checking rule: yaml:IndentationCheck
Got RuleProperty @org.sonar.check.RuleProperty(description=The indentation width, in spaces, type=, defaultValue=consistent, key=spaces)
Got RuleProperty @org.sonar.check.RuleProperty(description=Tells whether block sequences should be indented or not, type=, defaultValue=true, key=indent-sequences)
Got RuleProperty @org .sonar.check.RuleProperty(description=Tells whether to lint indentation in multi-line strings, type=, defaultValue=false, key=check-multi-line-strings)
YAMLLint config for rule yaml:IndentationCheck/indentation: '—
(repeat)

NullPointerException
at com.github.sbaudoin.yamllint.rules.Indentation.checkToken (Indentation.java:359)
at com.github.sbaudoin.yamllint.rules.Indentation.check (Indentation.java:214)
at com.github.sbaudoin.yamllint.Linter.getCosmeticProblems (Linter.java:230)
at com.github.sbaudoin.sonar.plugins.yaml.checks.YamlLintCheck.validate (YamlLintCheck.java:46)

```
steps to reproduce
mvn install -DskipTests
mvn sonar:sonar -X
(Suspect cause: we have some generated yaml files placed in target/classes/openapi, later used via classpath)

potential workaround
tried to disable the Indentation rule for yaml (yaml:IndentationCheck), did not work…

**Comment by roglar** [comment] 2020-02-03 16:38
might have ended up in wrong project - should probably be 'sonar-yaml'

**Comment by sbaudoin** [comment] 2020-02-03 21:54
Hello,

Thanks for reporting. On first sight, it looks like a bug of yamllint due to a strange YAML syntax but I need a reproduction case for that. Can you try to identify a simple reproduction scenario, please? You can manually run yamllint from the command line to test the tool against some of the generated files.

**Comment by roglar** [comment] 2020-02-04 10:24
```
summary: Response
value: {
  "JSON": {
    "A": "B"  # , missing
    "C": "D"
  }
} #
```

**Comment by sbaudoin** [comment] 2020-02-05 21:06
Thanks a lot, I'm going to debug with that and I let you know.

**Comment by sbaudoin** [comment] 2020-02-06 21:29
I cannot reproduce the error with yamllint only. Can you tell me what rule configuration you use?

**Comment by roglar** [comment] 2020-02-07 18:46
Default I think, downloaded it, built it, unpacked the .tar.gz.
cd into that catalog
./bin/yamllint erronous_file.yaml
CRASH!

Adding a ',' after "B" => no crash

Should I blame my ~/.m2/settings.xml ?

**Comment by sbaudoin** [comment] 2020-02-08 21:56
Thanks a lot for the details, that was really helpful. I can reproduce the issue know and I have found a type error (the NPE comes from `null` obviously not being assigned to an ìnt` variable: should be an `Integer` instead). But I still cannot reproduce the error in the unit tests (the errors found with the CLI is different from the unit tests), which lets me think there another error somewhere. Still investigating.

**Comment by sbaudoin** [comment] 2020-02-10 09:18
Found the problem: I poorly used assertions to do some runtime checks... The complete release process is going to take some days so thanks for being patient.

**Closed** 2020-02-10 16:56 UTC
Labels: bug

**Comment by sbaudoin** [comment] 2020-02-11 21:51
New SonarQube plugin released and available in the marketplace.
